In [2]:
import pandas as pd
import csv

In [3]:
df = pd.read_csv('split_leave_times/leave_times_53.csv', keep_default_na=True, sep=',\s+', delimiter=';', skipinitialspace=True)

FileNotFoundError: [Errno 2] File split_leave_times/leave_times_53.csv does not exist: 'split_leave_times/leave_times_53.csv'

In [3]:
df.head()

,DATASOURCE,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID,PASSENGERS,PASSENGERSIN,PASSENGERSOUT,DISTANCE,SUPPRESSED,JUSTIFICATIONID,LASTUPDATE,NOTE
0,DB,27-DEC-18 00:00:00,8581969,63,1143,67366,67366,67504,67516,2868361,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-19 17:45:34,NaN
1,DB,27-DEC-18 00:00:00,8589581,63,1143,68266,68266,67529,67539,3088374,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-19 17:45:34,NaN
2,DB,27-DEC-18 00:00:00,8576883,63,1143,84581,84581,83934,83945,2693280,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-19 17:45:34,NaN
3,DB,27-DEC-18 00:00:00,8581012,63,1143,77381,77381,77604,77621,2693278,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-19 17:45:34,NaN
4,DB,27-DEC-18 00:00:00,8581971,63,1143,79181,79181,79221,79234,2868361,NaN,NaN,NaN,NaN,NaN,NaN,09-JAN-19 17:45:34,NaN

,DATASOURCE - constant - delete
DAYOFSERVICE = convert to datetime
TRIPID - convert to category
PROGNUMBER = sequential position of the stop point in the trip - covert to category
STOPPOINTID - convert to category
PLANNEDTIME_ARR
PLANNEDTIME_DEP
ACTUALTIME_ARR
ACTUALTIME_DEP
VEHICLEID - category
PASSENGERS - empty - delete
PASSENGERSIN - empty - delete
PASSENEGERSOUT - empty - delete
SUPRESSED - delete
JUSTIFICATION - delete
LASTUPDATE - delete
NOTE - delete

In [4]:
del df['DATASOURCE']
df['DAYOFSERVICE'] = df['DAYOFSERVICE'].astype('datetime64[ns]')
df['TRIPID'] = df['TRIPID'].astype('category')
df['PROGRNUMBER'] = df['PROGRNUMBER'].astype('category')
df['STOPPOINTID'] = df['STOPPOINTID'].astype('category')
df['VEHICLEID'] = df['VEHICLEID'].astype('category')

del df['NOTE']
del df['LASTUPDATE']
del df['JUSTIFICATIONID']
del df['SUPPRESSED']
del df['PASSENGERS']
del df['PASSENGERSIN']
del df['PASSENGERSOUT']
del df['DISTANCE']

In [5]:
df.shape

(1833113, 9)

In [6]:
df.dtypes

DAYOFSERVICE       datetime64[ns]
TRIPID                   category
PROGRNUMBER              category
STOPPOINTID              category
PLANNEDTIME_ARR             int64
PLANNEDTIME_DEP             int64
ACTUALTIME_ARR              int64
ACTUALTIME_DEP              int64
VEHICLEID                category
dtype: object

In [7]:
df.head()

,DAYOFSERVICE,TRIPID,PROGRNUMBER,STOPPOINTID,PLANNEDTIME_ARR,PLANNEDTIME_DEP,ACTUALTIME_ARR,ACTUALTIME_DEP,VEHICLEID
0,2018-12-27,8581969,63,1143,67366,67366,67504,67516,2868361
1,2018-12-27,8589581,63,1143,68266,68266,67529,67539,3088374
2,2018-12-27,8576883,63,1143,84581,84581,83934,83945,2693280
3,2018-12-27,8581012,63,1143,77381,77381,77604,77621,2693278
4,2018-12-27,8581971,63,1143,79181,79181,79221,79234,2868361

In [8]:
df.to_csv('Leavetimes53_Cleaned.csv', index=False)